[settings]
ps_endpoints => pgsql,pbx_conn,ps_endpoints
ps_auths => pgsql,pbx_conn,ps_auths
ps_aors => pgsql,pbx_conn,ps_aors
ps_contacts => pgsql,pbx_conn,ps_contacts
ps_domain_aliases => pgsql,pbx_conn,ps_domain_aliases