[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5080
external_media_address=100.88.43.14
external_signaling_address=100.88.43.14

; Kamailio trunk - used by Asterisk to send calls back through Kamailio
[kamailio-trunk]
type=endpoint
transport=transport-udp
context=from-kamailio
aors=kamailio-trunk
outbound_proxy=sip:127.0.0.1:5060
allow=!all,ulaw,alaw
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[kamailio-trunk]
type=aor
contact=sip:127.0.0.1:5060

[kamailio-trunk]
type=identify
endpoint=kamailio-trunk
match=127.0.0.1/32