[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=100.88.43.14
external_signaling_address=100.88.43.14

[endpoint-user](!)
type=endpoint
context=internal
disallow=all
allow=ulaw
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
direct_media=no

[101](endpoint-user)
type=endpoint
auth=101
aors=101

[101]
type=auth
auth_type=userpass
username=101
password=101pass

[101]
type=aor
max_contacts=1

[102](endpoint-user)
type=endpoint
auth=102
aors=102

[102]
type=auth
auth_type=userpass
username=102
password=102pass

[102]
type=aor
max_contacts=1