[general]
format=wav49|wav
maxsilence=2
silencethreshold=128
maxlogins=3
serveremail=asterisk@pbx.local
attach=yes
skipms=3000
maxsecs=300
minsecs=3

[default]
; Alpha Corp (t1)
t1_101 => 1234,Alpha User 101,,
t1_102 => 1234,Alpha User 102,,

; Beta Inc (t2)
t2_101 => 1234,Beta User 101,,
t2_102 => 1234,Beta User 102,,
