global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - '127.0.0.1:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9091']

  - job_name: 'api'
    static_configs:
      - targets: ['127.0.0.1:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['127.0.0.1:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['127.0.0.1:9187']

  - job_name: 'asterisk-1'
    static_configs:
      - targets: ['127.0.0.1:9500']

  - job_name: 'asterisk-2'
    static_configs:
      - targets: ['127.0.0.1:9501']

  # Currently asterisk-exporter is omitted until we deploy it (runs on 9500), configure later.
