-- AOR (Address of Record): Defines where endpoints register and how contacts are managed.
CREATE TABLE ps_aors (
    id VARCHAR(40) PRIMARY KEY,
    contact VARCHAR(255),
    default_expiration INT,
    mailboxes VARCHAR(80),
    max_contacts INT,
    minimum_expiration INT,
    remove_existing BOOLEAN,
    qualify_frequency INT,
    authenticate_qualify BOOLEAN,
    maximum_expiration INT,
    outbound_proxy VARCHAR(256),
    support_path BOOLEAN,
    qualify_timeout FLOAT,
    voicemail_extension VARCHAR(40)
);

-- AUTH: Stores credentials used for registration and SIP challenges.
CREATE TABLE ps_auths (
    id VARCHAR(40) PRIMARY KEY,
    auth_type VARCHAR(20),
    nonce_lifetime INT,
    md5_cred VARCHAR(40),
    password VARCHAR(80),
    realm VARCHAR(40),
    username VARCHAR(40)
);

-- ENDPOINTS: The main configuration for SIP accounts/peers.
CREATE TABLE ps_endpoints (
    id VARCHAR(40) PRIMARY KEY,
    transport VARCHAR(40),
    aors VARCHAR(200),
    auth VARCHAR(40),
    context VARCHAR(40),
    disallow VARCHAR(200),
    allow VARCHAR(200),
    direct_media BOOLEAN,
    connected_line_method VARCHAR(40),
    direct_media_method VARCHAR(40),
    direct_media_glare_mitigation VARCHAR(40),
    disable_direct_media_on_nat BOOLEAN,
    dtmf_mode VARCHAR(20),
    external_media_address VARCHAR(40),
    force_rport BOOLEAN,
    ice_support BOOLEAN,
    identify_by VARCHAR(40),
    mailboxes VARCHAR(40),
    moh_suggest VARCHAR(40),
    outbound_auth VARCHAR(40),
    outbound_proxy VARCHAR(256),
    rewrite_contact BOOLEAN,
    rtp_ipv6 BOOLEAN,
    rtp_symmetric BOOLEAN,
    send_pai BOOLEAN,
    send_rpid BOOLEAN,
    timers_min_se INT,
    timers VARCHAR(40),
    timers_sess_expires INT,
    callerid VARCHAR(40),
    send_diversion BOOLEAN,
    userinfo_to_contact BOOLEAN,
    webrtc BOOLEAN,
    dtls_verify VARCHAR(40),
    dtls_rekey INT,
    dtls_cert_file VARCHAR(200),
    dtls_private_key VARCHAR(200),
    dtls_cipher VARCHAR(200),
    dtls_ca_file VARCHAR(200),
    dtls_ca_path VARCHAR(200),
    dtls_setup VARCHAR(40),
    srtp_tag_32 BOOLEAN,
    media_encryption VARCHAR(40),
    use_avpf BOOLEAN,
    force_avp BOOLEAN,
    media_use_received_transport BOOLEAN,
    one_touch_recording BOOLEAN,
    record_on_feature VARCHAR(40),
    record_off_feature VARCHAR(40),
    rtp_engine VARCHAR(40),
    allow_transfer BOOLEAN,
    sdp_owner VARCHAR(40),
    sdp_session VARCHAR(40),
    tos_audio INT,
    tos_video INT,
    sub_min_expiry INT,
    from_domain VARCHAR(40),
    from_user VARCHAR(40),
    mwi_from_user VARCHAR(40),
    call_group VARCHAR(40),
    pickup_group VARCHAR(40),
    named_call_group VARCHAR(40),
    named_pickup_group VARCHAR(40),
    device_state_busy_at INT,
    t38_udptl BOOLEAN,
    t38_udptl_ec VARCHAR(40),
    t38_udptl_maxdatagram INT,
    t38_fax_maxrate INT,
    t38_udptl_nat BOOLEAN,
    t38_udptl_ipv6 BOOLEAN,
    tone_zone VARCHAR(40),
    language VARCHAR(40),
    one_touch_recording_dtmf_duration INT,
    inband_progress BOOLEAN,
    call_group_channels INT,
    media_address VARCHAR(40),
    redirect_method VARCHAR(40),
    set_var VARCHAR(800),
    cos_audio INT,
    cos_video INT,
    message_context VARCHAR(40),
    force_avp_on_hold BOOLEAN,
    rpid_immediate BOOLEAN
);

-- CONTACTS: Active registrations (automatically populated and maintained by Asterisk)
CREATE TABLE ps_contacts (
    id VARCHAR(255) PRIMARY KEY,
    uri VARCHAR(511),
    expiration_time BIGINT,
    qualify_frequency INT,
    outbound_proxy VARCHAR(256),
    path TEXT,
    user_agent VARCHAR(255),
    qualify_timeout FLOAT,
    reg_server VARCHAR(20),
    authenticate_qualify BOOLEAN,
    via_addr VARCHAR(40),
    via_port INT,
    call_id VARCHAR(255),
    endpoint VARCHAR(40),
    prune_on_boot BOOLEAN
);

-- DOMAIN ALIASES: Defines alternative domains for multi-tenant environments.
CREATE TABLE ps_domain_aliases (
    id VARCHAR(40) PRIMARY KEY,
    domain VARCHAR(80)
);